### ISSUE TITLE
Error VPC Does not Exist when it does during Terraform Apply - Windows Server 2019

### ISSUE THREAD

**Issue by chathamdl** [TechToSpeech/terraform-aws-serverless-static-wordpress#10]
Using Screenshotted Code in main.tf and provider.tf I get the VPC Error below.  Error says VPC does not exist when it clearly does in my AWS Account.  Thanks again Pete, love this code and what it is gonna do for me.  Also enjoying figuring this out.  
Note: The code has provisioned alot in my account successfully just stuck on this thing.

### Error 
![image](https://user-images.githubusercontent.com/22111072/123198799-b5237d80-d47b-11eb-8852-9d8b87b22fcb.png)

### VPC in AWS Account in us-east-1
![image](https://user-images.githubusercontent.com/22111072/123198974-059adb00-d47c-11eb-800f-6c70d27232ca.png)

Main.TF -1 - Account ID hidden on purpose
![image](https://user-images.githubusercontent.com/22111072/123199457-e81a4100-d47c-11eb-8ca4-221cf7c3b11c.png)

Main.TF -2
![image](https://user-images.githubusercontent.com/22111072/123199058-2a8f4e00-d47c-11eb-82ee-59312f0b22cc.png)

Provider.TF
![image](https://user-images.githubusercontent.com/22111072/123199318-a2f60f00-d47c-11eb-991b-956c09dd8083.png)

**Comment by petewilcock** [comment]
Which region is configured in your AWS default profile? Type 'aws configure' to check. It must be your desired region.

**Comment by chathamdl** [comment]
us-east-1  See screenshot to confirm.  I did some looking in the ecs files and found the lines of code that it errors on and nothing stood out that made me think it was switching regions, but I agree that is the only thing that makes sense.

![image](https://user-images.githubusercontent.com/22111072/123278038-9dc4ae80-d4d4-11eb-8ead-20fc7c123d60.png)

**Comment by petewilcock** [comment]
Do you have more than one profile set up?

can you try this: `set AWS_DEFAULT_REGION=us-east-1` and see if that works?

set assumes you're running this Windows cmd shell, otherwise use EXPORT for linux. 

Just also search your code for `eu-west-1` anywhere... really stumped here. 

One other alternative would be to insert your VPC ID as a data reference by adding this:

````

data "aws_vpc" "selected" {
}
``

and then:

`main_vpc_id = data.aws_vpc.selected.id`

If you have only one VPC (the default), this should work. The only strange thing with that is that if you are somehow in the wrong region, it will try to create those security groups there - but that might be informative as to what's going on.

**Comment by chathamdl** [comment]
Pete I think a found it and you helped me again via google.  I found that I had eu-west-2 defined as aws region as well as us-east-1 since it was in the example files, so I cleaned that up and then kept getting prompted for region like it was not seeing it.  So on to google I went where I found this where in 2018 you provided resolution to the region prompt.  I will run the apply again and hope to see this resolved if not I will do as described above and reply either way.  

https://github.com/hashicorp/terraform-provider-aws/issues/1043

**Comment by chathamdl** [comment]
This is what I did in my provider file.
![image](https://user-images.githubusercontent.com/22111072/123293330-e3d43f00-d4e1-11eb-8495-790541ac32ae.png)

**Comment by petewilcock** [comment]
lol, great! I somehow provided the solution myself from over 3 years in the past. This says _something_ about my experience with Terraform. 

I will update the documentation to make this requirement clear. Thanks!

**Comment by chathamdl** [comment]
That looks like it did it thanks man.
![image](https://user-images.githubusercontent.com/22111072/123294422-d2d7fd80-d4e2-11eb-8641-d26d3a6f56eb.png)
