### ISSUE TITLE
Really struggling to get this working...

### ISSUE THREAD

**Issue by SChubb** [TechToSpeech/terraform-aws-serverless-static-wordpress#46]
Hi,

Love the idea of this, but I'm really struggling to get the Terraform module working - any ideas would be great!

I cloned this GitHub repository, then opened the main.tf file in the docs/examples folder.

Updated the various settings - including setting the locals.profile value to a valid AWS CLI profile that has full Admin rights to the AWS account in question. (this profile works in the AWS CLI and the secret doesn't start with + or any other non-alphanumeric character as I read that this can cause an issue)

I ran Terraform plan - which gave an error as various modules weren't installed and to run a Terraform init
So ran Terraform init on that folder - when it finished installing
Ran Terraform plan again and got this error:

`Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.     
│       status code: 403, request id: 1065464e-1b5d-4735-96e7-4aa6b19e727c
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on provider.tf line 13, in provider "aws":
│   13: provider "aws" {
╵
╷
│ Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.     
│       status code: 403, request id: 6cca823c-9c4c-4995-b71f-3b46995cfe9a
│
│   with provider["registry.terraform.io/hashicorp/aws"].ue1,
│   on provider.tf line 17, in provider "aws":
│   17: provider "aws" {`

And haven't managed to get any further - any ideas?

**Comment by petewilcock** [comment]
This sounds very much an issue in your Terraform set-up, my best advice would be to read this docs page thoroughly and see the many different ways Terraform can discover your credentials: https://registry.terraform.io/providers/hashicorp/aws/latest/docs
