### ISSUE TITLE
Code Build Fails on line 62 of main.tf under CodeBuild Module

### ISSUE THREAD

**Issue by chathamdl** [TechToSpeech/terraform-aws-serverless-static-wordpress#7]
Error I get when executing Terraform Init, validate, and plan.  I Created a Blank Dir on Windows Server 2019 and Copied the text from your example code and modified it for my aws environment.  See Screenshots Attached.  I will admit I am new to Terraform, so maybe I am missing something small.  I had to split my Main.tf into 2 screenshots.

main.tf -1
![image](https://user-images.githubusercontent.com/22111072/123033996-b6d73d80-d3b6-11eb-8302-db5d7532ace1.png)

main.tf -2 
![image](https://user-images.githubusercontent.com/22111072/123033907-8d1e1680-d3b6-11eb-8555-61920f93725f.png)

provider.tf
![image](https://user-images.githubusercontent.com/22111072/123033964-a6bf5e00-d3b6-11eb-862a-2cef07114047.png)

Directory Structure on Server
![image](https://user-images.githubusercontent.com/22111072/123034141-00c02380-d3b7-11eb-8846-7a72e82f1e63.png)

Appears to Pull code just fine, seems to have trouble pulling the zip file in Error
![image](https://user-images.githubusercontent.com/22111072/123033462-ca35d900-d3b5-11eb-91e8-139bda158377.png)

**Comment by petewilcock** [comment]
Please make sure you are using latest version (currently 0.1.1) - this has a fix for that issue seen :) 

I will update examples to latest version.

**Comment by chathamdl** [comment]
pete thanks will do sir and I will let you know.

**Comment by chathamdl** [comment]
That is looking much better no errors on this run.  I am gonna hit apply and let you know how it goes!!!

**Comment by chathamdl** [comment]
This issue is resolved.  But hitting another issue where it is complaining about my vpc not existing when it clearly does.  New issue post coming.
