### ISSUE TITLE
Local-exec provisioner error with docker push-pull

### ISSUE THREAD

**Issue by Ojaybee** [TechToSpeech/terraform-aws-serverless-static-wordpress#9]
I'm running windows with docker installed and running but the docker push-pull is failing. For the aws profile I'm using "default". Here's the error message:
![image](https://user-images.githubusercontent.com/6020098/123096029-947d0880-d426-11eb-84eb-dd66ef0bf8e6.png)

**Comment by petewilcock** [comment]
I have just released 0.0.7 of [terraform-ecr-mirror](https://registry.terraform.io/modules/TechToSpeech/ecr-mirror/aws/latest).

Please update to this and try again. I believe this is a Windows-specific issue.

**Comment by Ojaybee** [comment]
Updating to 0.0.7 now throws a "bad interpreter" error:

![image](https://user-images.githubusercontent.com/6020098/123106208-5ab0ff80-d430-11eb-85f4-92cdb437365f.png)

**Comment by petewilcock** [comment]
Do you have bash or Gitbash installed and on your PATH?

**Comment by Ojaybee** [comment]
Yes, bash command works on test scripts:

![image](https://user-images.githubusercontent.com/6020098/123110942-73bbaf80-d434-11eb-911a-3ff004ae23c1.png)

**Comment by petewilcock** [comment]
This looks like another Windows line-error issue: 

https://askubuntu.com/questions/304999/not-able-to-execute-a-sh-file-bin-bashm-bad-interpreter

Did you clone the repository for the module, or install it via Terraform? It seems that cloning it with Git on Windows can cause issues depending on your git settings.

**Comment by Ojaybee** [comment]
I installed the ECR module via Terraform.

**Comment by petewilcock** [comment]
Could you try opening  `docker_pullpush.sh`  in Notepad++ on your local cache on of the ecr-mirror module? 

The bottom-right of the screen will confirm which line-endings are being used for this file:

![image](https://user-images.githubusercontent.com/6526265/123121473-1841ef80-d43d-11eb-8852-e7cb495e2810.png)

This is very confusing, all issues at the moment seem to be windows-based :(

**Comment by Ojaybee** [comment]
Getting closer. I used SublimeText to change the line endings of the local cache `docker_pullpush.sh` (view > line endings > unix) and have got further. "local-exec" was fine but I've now run into a problem with my WSL2 distro and Docker. I don't have a distro installed and Microsoft Store isn't working similar problem to here:

https://www.thewindowsclub.com/microsoft-store-get-button-does-not-work

Looking at this output installing a distro should work. 

![image](https://user-images.githubusercontent.com/6020098/123130103-660e2600-d444-11eb-84bf-88c96006ce9a.png)

Just remember none of the linux users have any issues because linux :)

**Comment by Ojaybee** [comment]
Getting further. Push pull is pulling but has trouble with `basic auth credentials`. 

![image](https://user-images.githubusercontent.com/6020098/123146334-a629d480-d455-11eb-9f10-4533ed27640c.png)

**Comment by petewilcock** [comment]
I think the next release of this will need to provide a pre-built image as an option :) Here's some quickstart instructions on setting up the awi-cli (which is what you're missing here)

*   [Install the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html). We’ll need this to authenticate operations in AWS via Terraform. 
*   [Create a user](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html#id_users_create_console) as ‘Programmatic Access’ user and assign it ‘ECRFullAccess’ permissions, and then generate an [AWS Access Key and Secret Key](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html). 
* [Configure the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) with the Access Key and Secret Key you just generated.

**Comment by Ojaybee** [comment]
AWS Cli is set up correctly with full access to ECR on that profile but I'm still getting the same error `Error: Cannot perform an interactive login from a non TTY device`

**Comment by petewilcock** [comment]
You need awscli v2.

**Comment by Ojaybee** [comment]
Yes, I'm running awscli v2. 

![image](https://user-images.githubusercontent.com/6020098/123216690-b8d9f300-d4c1-11eb-8bf1-7954b5dfd891.png)

**Comment by fededalla2** [comment]
I was able to run everything by referencing the remote terraform modules, I had to instal WSL version 2 with an AWS CLI 2 also, ran successful but when trigerring the ECS Task still fails with the same error message. I tried twice, deleting all ECS Images and Builds just in case but without any luck.
